# Generated by Django 4.1.4 on 2023-06-20 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_alter_author_table_alter_book_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table=None,
        ),
        migrations.AlterModelTable(
            name='book',
            table=None,
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='genre',
            table=None,
        ),
    ]
